name: Publish Release

on:
    push:
        branches:
            - master

env:
    GITHUB_TARGET_REPO: "https://maven.martmists.com/snapshots"
    GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
    GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    DEPLOY_TYPE: "snapshot"
    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
    build-libraries:
        strategy:
            matrix:
                host: [ ubuntu-latest, windows-latest, macos-latest ]
                python: [ '3.9', '3.10' ]
        runs-on: ${{ matrix.host }}
        steps:
            # Check out project
            - uses: actions/checkout@v2

            # Set up java
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - shell: bash
              run: |-
                  wget $(curl "https://packages.msys2.org/package/mingw-w64-x86_64-python${{ matrix.python }}?repo=mingw64" | grep -Po "(?<=>)https://mirror.msys2.org/.+?.zst") --output-file pkg.tar.zst
                  tar --use-compress-program=unzstd -xvf pkg.tar.zst
              working-directory: kpy-library

            # Set up python
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python }}

            # Set up gradle
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1

            # Build all
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: -PpythonVersion=${{ matrix.python }}  build

            # Publish modules
            - name: Publish to Maven
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: publish
