name: Publish Snapshot

on:
    push:
        paths:
            - '**.kt'
            - '**.kts'
            - '**.yaml'
            - '**.py'
            - '**.properties'
        branches:
            - master

env:
    GITHUB_TARGET_REPO: "https://maven.martmists.com/snapshots"
    GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
    GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    DEPLOY_TYPE: "snapshot"
    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
    test-sample:
        strategy:
            matrix:
                python: [ '3.9', '3.10' ]
                os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        runs-on: ${{ matrix.os }}
        steps:
            # Check out project
            - uses: actions/checkout@v2

            # Set up java
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            # Set up python
            -   uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python }}

            # Note: grep installs as ggrep on macos
            - shell: bash
              name: Download msys2 python headers
              if: ${{ matrix.os }} == 'macos-latest'
              run: |
                  brew install grep
                  wget $(curl "https://packages.msys2.org/package/mingw-w64-x86_64-python${{ matrix.python }}?repo=mingw64" | ggrep -Po "(?<=>)https://mirror.msys2.org/.+?.zst") -O pkg.tar.zst
                  tar --use-compress-program=unzstd -xvf pkg.tar.zst
              working-directory: kpy-library

            - shell: bash
              name: Download msys2 python headers
              if: ${{ matrix.os }} == 'ubuntu-latest'
              run: |
                  wget $(curl "https://packages.msys2.org/package/mingw-w64-x86_64-python${{ matrix.python }}?repo=mingw64" | grep -Po "(?<=>)https://mirror.msys2.org/.+?.zst") -O pkg.tar.zst
                  tar --use-compress-program=unzstd -xvf pkg.tar.zst
              working-directory: kpy-library

            # Build all
            - shell: bash
              name: Build sample
              run: python kpy-sample/setup.py install --user

    build-libraries:
        strategy:
            matrix:
                python: [ '3.9', '3.10' ]
        runs-on: macos-latest
        needs: test-sample
        steps:
            # Check out project
            - uses: actions/checkout@v2

            # Set up java
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            # Set up python
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python }}

            # Note: grep installs as ggrep on macos
            - shell: bash
              name: Download msys2 python headers
              run: |
                  brew install grep 
                  wget $(curl "https://packages.msys2.org/package/mingw-w64-x86_64-python${{ matrix.python }}?repo=mingw64" | ggrep -Po "(?<=>)https://mirror.msys2.org/.+?.zst") -O pkg.tar.zst
                  tar --use-compress-program=unzstd -xvf pkg.tar.zst
              working-directory: kpy-library

            # Build all
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: -PpythonVersion=${{ matrix.python }} build

            # Publish modules
            - name: Publish to Maven
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: -PpythonVersion=${{ matrix.python }} publish
