name: Publish Snapshot

on:
  push:
    paths:
      - '**.kt'
      - '**.kts'
      - '**.yaml'
      - '**.py'
      - '**.properties'
    branches:
      - master

env:
  GITHUB_TARGET_REPO: "https://maven.martmists.com/snapshots"
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
  DEPLOY_TYPE: "snapshot"
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
  build-libraries:
    strategy:
      matrix:
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        runner-os:
          - 'windows-latest'
          - 'ubuntu-latest'
    #          - 'macos-latest'
    runs-on: {{ matrix.runner-os }}
    steps:
      # Check out project
      - uses: actions/checkout@v2

      # Set up java
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan

      # Build all
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -PpythonVersion=${{ matrix.python }} build

      # Publish modules
      - name: Publish to Maven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -PpythonVersion=${{ matrix.python }} publish
