name: Publish Release

on:
    push:
        tags:
            - '*'

env:
    GITHUB_TARGET_REPO: "https://maven.martmists.com/releases"
    GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
    GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    DEPLOY_TYPE: "release"
    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
    build-libraries:
        strategy:
            matrix:
                host: [ ubuntu-latest, windows-latest, macos-latest ]
                python: [ '3.9', '3.10' ]
        runs-on: ${{ matrix.host }}
        steps:
            # Check out project
            - uses: actions/checkout@v2

            # Set up java
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            # Set up python
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python }}

            # Set up gradle
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1

            # Build all
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: build

            # Publish modules
            - name: Publish to Maven
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: publish

    build-plugin:
        runs-on: ubuntu-latest
        steps:
            # Check out project
            - uses: actions/checkout@v2

            # Set up java
            - uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            # Set up python
            - uses: actions/setup-python@v3
              with:
                  python-version: '3.9'

            # Set up gradle
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1

            # Build all
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: build

            # Publish plugin
            - name: Publish to Gradle Plugin Repository
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: publishPlugins
